from typing import Any, Callable

class CliStrategy: ...

class _CliCommand:
    def command(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def group(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], "_CliCommand"]: ...

class _Cli:
    def command(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def group(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], _CliCommand]: ...
    def argument(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

cli: _Cli
