from typing import Any

class TestResponse:
    status_code: int
    content: bytes
    headers: dict[str, str]
    def json(self) -> Any: ...

class TestClient:
    def __init__(self, app: Any) -> None: ...
    def get(self, path: str, *args: Any, **kwargs: Any) -> TestResponse: ...
    def post(self, path: str, *args: Any, **kwargs: Any) -> TestResponse: ...
    def delete(self, path: str, *args: Any, **kwargs: Any) -> TestResponse: ...

