from typing import Any, Callable

class RestApi:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def use(self, middleware: Any) -> Any: ...
    def guard(self, pattern: str, callback: Callable[..., Any]) -> Any: ...
    def init(self, path: str, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def group(self, path: str, *args: Any, **kwargs: Any) -> "RestApi": ...

